### ISSUE TITLE
problem with sync at 2.3 ckan 

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/ckanext-odn-ic2pc-sync#12]
Dataset exists with resource - zip, url (sparql endpoint)
When a user press publish catalog now then he gets a message down 

The displayed message:

```
Error occured while synchronizing external catalog:

    public catalog - [Creating / updating resource with name ''] 
```

**Comment by mvi-eea-sk** [comment]
All resources are required to have their name set.

**Comment by Jan-Marcek** [comment]
confirmed - One of the resources didn't have set name.

**Comment by skrchnavy** [comment]
@Jan-Marcek : Is it related only to ckan 2.3 or valid also for other versions?
@mvi-eea-sk : there shall be better error message with explanation what is wrong. Shall not block synchronisation of other resources.

**Comment by Jan-Marcek** [comment]
It is not related to ckan. It's a bug in ckanext-odn-ic2pc-sync.

**Comment by mvi-eea-sk** [comment]
fixed:
- failing to sync one resource will not stop sync of other resource
- for each failure will show proper msg
- proper error msg when resource is missing name
