### ISSUE TITLE
ckanext-odn-ic2pc-sync doesn't support certificate validation

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/ckanext-odn-ic2pc-sync#15]
due to https://github.com/OpenDataNode/odn-box/commit/9cf5b556556282e026a0cc679e7292321dfd28a2 ckanext-odn-ic2pc-sync has to support https.

Now, the certificate validation is [disabled](https://github.com/OpenDataNode/odn-ckancommons/commit/1554619524934fb29d6435036b28d3f830dffea9)  when connection is https.

ckanext-odn-ic2pc-sync uses urllib2 and requests. urllib2 by default doesn't do certificate verification but requests does.

**Comment by Jan-Marcek** [comment]
Python's lib requests has his own list of trusted CAs. We can't rely on OS trusted list.

**Comment by Jan-Marcek** [comment]
method [ssl.create_default_context](https://docs.python.org/2/library/ssl.html#ssl.create_default_context) could help to read os certs.
but  `SSLContext was introduced in 2.7.9,` from http://stackoverflow.com/questions/28228214/ssl-module-object-has-no-attribute-sslcontext.

Debian Wheezy 7 uses older version of python. Debian 8 Jessie uses 2.7.9..

`wheezy (oldstable) (python): interactive high-level object-oriented language (default version) 
2.7.3-4+deb7u1: all
jessie (stable) (python): interactive high-level object-oriented language (default version) 
2.7.9-1: amd64 arm64 armel armhf i386 mips mipsel powerpc ppc64el s390x 
` from https://packages.debian.org/search?keywords=python

**Comment by Jan-Marcek** [comment]
`urllib2.urlopen` (https://github.com/OpenDataNode/odn-ckancommons/blob/ODN_v1.0.2/odn_ckancommons/ckan_helper.py#L31 ) doesn't support verification in version 2.7.3  from [urllib2.html](https://docs.python.org/release/2.7.3/library/urllib2.html?highlight=urllib2#urllib2)

**Comment by Jan-Marcek** [comment]
summary:
As I wrote before, certification validation is not supported in the plugin. There are used two libraries: urlib2 and request. urllib2 doesn't even support certification validation. If we want to fix it we have to use Debian 8 Jessie where is higher version of urllib2 which support certification validation.

**Comment by hanecak** [comment]
OK, so this is blocked by upgrade to Debian 8 - see https://github.com/OpenDataNode/open-data-node/issues/238 .

**Comment by Jan-Marcek** [comment]
For now, we disabled cert validation in updating resource, because https://github.com/OpenDataNode/open-data-node/issues/261

**Comment by Jan-Marcek** [comment]
Now, cert validation is allowed in updating resource.

**Comment by Jan-Marcek** [comment]
The problem occoures again: https://github.com/OpenDataNode/open-data-node/issues/261. 
Now, cert validation is disabled in updating resource.
