### ISSUE TITLE
Server Error after Add catalog action

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/ckanext-odn-ic2pc-sync#18]
Based on https://github.com/OpenDataNode/open-data-node/issues/162

All entered data are at the picture. Pushed button verify.
![image](https://cloud.githubusercontent.com/assets/10993265/8569847/edeaf126-257b-11e5-9f6a-480d36d365d1.png)

version: https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/tree/ODN_v1.1.0

**Comment by mvi-eea-sk** [comment]
fixed in https://github.com/OpenDataNode/odn-ckancommons/commit/9099b7a1e1a02462355f7e55b28c8db7d15cf9b5
