### ISSUE TITLE
it doesn't support synchronization of datastore between external (3rd party) catalog 

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/ckanext-odn-ic2pc-sync#21]
The datastore resources are not correctly synchronized between catalog on host A and catalog on host B. They look like broken url.
![bug](https://cloud.githubusercontent.com/assets/5822680/9487375/4a15664a-4bd1-11e5-94a5-486e8536b233.png)

Version: 0.6.0
provided by odn-ckan-shared@2.3-odn1.1.0 0

**Comment by mvi-eea-sk** [comment]
@Jan-Marcek can you check if you can replicate this issue with the latest version?
If the problem problem persists, how can i replicate it?
1. Its synchronization to public or external catalog?
2. Was it manual or automatic synchronization?
3. Was the dataset in B set as private?
4. Was there some errors (A and B too) in the error log file?
5. Did you try manual synchronization? It will display error that occurred, automatic will only write it to error log file.

**Comment by Jan-Marcek** [comment]
The problem was that SQL resource contained the diacritics characters. It was fixed in ckan core.
