### ISSUE TITLE
Problem in external catalog sync after upgrade to version (ODN) 1.2.4

### ISSUE THREAD

**Issue by hanecak** [OpenDataNode/ckanext-odn-ic2pc-sync#25]
From the support mailing list:

> After upgrade to version  1.2.4, sync to external public catalog after running a pipeline is not working anymore.
> 
> In the odn-ckan-ic.error.log
> 
> [Tue May 10 17:26:54 2016] [error] 2016-05-10 17:26:54,768 DEBUG [ckanext] sync to dataset specified external catalogs (1)
> [Tue May 10 17:26:54 2016] [error] 2016-05-10 17:26:54,769 DEBUG [ckanext] sync to catalog = http://test.dati.umbria.it
> [Tue May 10 17:26:54 2016] [error] 2016-05-10 17:26:54,769 ERROR [ckanext] 'private'
> [Tue May 10 17:26:54 2016] [error] Traceback (most recent call last):
> [Tue May 10 17:26:54 2016] [error]   File "/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckanext/publishing/plugin.py", line 178, in sync_ext_catalog
> [Tue May 10 17:26:54 2016] [error]     elif dataset['private']:
> [Tue May 10 17:26:54 2016] [error] KeyError: 'private'
> [Tue May 10 17:26:54 2016] [error] 2016-05-10 17:26:54,773 DEBUG [ckanext] <<< end of synchronization
> 
> Changing line 178 of  /usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckanext/publishing/plugin.py
> 
> From:
>            elif dataset['private']:
> To:
>    elif 'private' in dataset and dataset['private']:
> 
> apparently fixes the issue
> 
> Regards,
> Azzurra

Original message: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/odn-support/4XLZu8TJqR4/0Q9mYPGrIgAJ

So, the issue affects [ODN 1.2.4](https://github.com/OpenDataNode/open-data-node/releases/tag/ODN_v1.2.4) / [ODN-IC2PC-SYNC v1.2.3](https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/releases/tag/ODN_v1.2.3) and offending line comes from bd7531f7023acd679d996df5e213ee75a409b034 .

**Comment by mvi-eea-sk** [comment]
fixed in https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/commit/acd245530de6d095c3af80b628c0758413a66567

@Jan-Marcek can you please set milestone to release / version in which the fix will be included?
